-- up
CREATE TABLE users (id SERIAL PRIMARY KEY, email TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), placed_at TIMESTAMP NOT NULL DEFAULT NOW());

-- down
DROP TABLE orders;
DROP TABLE users;
